var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
var app = builder.Build();
app.UseSwagger();
app.UseSwaggerUI(c => { c.SwaggerEndpoint("/swagger/v1/swagger.json", "Girisim & Yatirim API v1"); c.RoutePrefix = "swagger"; });
app.MapGet("/", () => "Girisim & Yatirim API Canli Ortamda Calisiyor!");
app.UseAuthorization();
app.MapControllers();
app.Run();
